config/routes.rb
Rails.application.routes.draw do
  resources :assets
  resources :reservations
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'reservations#index'
end

app/models/reservation.rb
class Reservation
  #< ApplicationRecord
  include ActiveModel::Model

  #belongs_to :user
  #belongs_to :asset

  attr_accessor :id,:name,:start_time,:end_time,:notes,:approved,:approval_id,:asset,:user

  attr_accessor :asset_id
  attr_accessor :server_name,:start_date,:end_date,:approved

  @@reservations=nil

  def initialize(attributes={})
    super
  end

  def self.order(by)
    if @@reservations.nil?
      @@reservations = self.all
    end
    @@reservations
  end

  def self.all
    reservations = []
    num = 1
    response = RestClient.get self.uri, :accept=>:json
    json = JSON.parse(response)
    json.each do |s|

      hh = Hash.new
      hh['id'] = s['name']

      tt = s["start_date"].to_i / 1000
      hh['start_time'] = Time.at(tt).to_datetime
      tt = s["end_date"].to_i / 1000
      hh['end_time'] = Time.at(tt).to_datetime

      hh['approved'] = s['approved']
      hh['approval_id'] = s['approval_id']

      hh['asset'] = Asset.new(id:s['server_name'],name:s['server_name'])
      hh['user']  = User.new do |u|
        u.email = 'anonymous@reservate.com'
      end

      hh['notes'] = s['name']

      reservation = Reservation.new(hh)
      #reservation.asset =
      reservations << reservation
      num += 1
    end
    reservations
  end

  def self.find(id)
    #path = "%s/%s" % [self.uri, id]
    #response = RestClient.get self.uri, :accept=>:json
    #hh = JSON.parse(response)
    #h2 = self.reverse_map(hh)
    #reservation = Reservation.new(h2)
    reservation = nil
    reservations = self.all
    reservations.each do |res|
      if res.id == id
        reservation = res
      end
    end
    reservation
  end

  def destroy
    path = "%s/%s" % [Reservation.uri, self.id]
    response = RestClient.delete path, :accept=>:json
  end

  def self.reverse_map(s)
    hh = {}
    hh['id'] = s['name']

    hh['start_time'] = s["start_date"]
    hh['end_time'] = s["end_date"]
    hh['approved'] = s['approved']
    hh['approval_id'] = s['approval_id']

    hh['asset'] = Asset.new(id:s['server_name'],name:s['server_name'])
    hh['user']  = User.new do |u|
      u.email = 'anonymous@reservate.com'
    end

    hh['notes'] = s['name']
    hh
  end

  def self.map_params(params)
    hh = {}
    hh[:name] = params['notes']
    hh['start_date'] = DateTime.new(params["start_time(1i)"].to_i,
                                    params["start_time(2i)"].to_i,
                                    params["start_time(3i)"].to_i,
                                    params["start_time(4i)"].to_i,
                                    params["start_time(5i)"].to_i)

    hh['end_date'] = DateTime.new(params["end_time(1i)"].to_i,
                                  params["end_time(2i)"].to_i,
                                  params["end_time(3i)"].to_i,
                                  params["end_time(4i)"].to_i,
                                  params["end_time(5i)"].to_i)

    hh['server_name'] = params['asset_id']
    hh['approved'] = false
    hh
  end

  # @return [Object]
  def save
    response = RestClient.post Reservation.uri, self.to_json, :content_type=>:json, :accept=>:json
    print response
    true
  end

  def persisted?
    if id.nil?
      false
    else
      true
    end
  end

  def self.uri
    'http://raj-tmp.ddns.me/api/reservations'
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.order(:asset_id)
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create

    params = Reservation.map_params(reservation_params)
    @reservation = Reservation.new(params)

    @reservation.user = current_user
      
    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:user_id, :asset_id, :start_time, :end_time, :notes)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_for(reservation) do |f| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :asset_id %>
    <%= f.collection_select :asset_id, Asset.order(:id),:id,:name, include_blank: true %>
  </div>
  <br/>
  <div class="field">
    <%= f.label :start_time %>
    <%= f.datetime_select :start_time %>
  </div>
    <br/>
  <div class="field">
    <%= f.label :end_time %>
    <%= f.datetime_select :end_time %>
  </div>
    <br/>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :notes %>
  </div>
    <br/>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservations</h1>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>User</th>
      <th>Asset</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.user.email %></td>
        <td><%= reservation.asset.name %></td>
        <td><%= reservation.start_time %></td>
        <td><%= reservation.end_time %></td>
        <td><%= reservation.notes %></td>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Modify', edit_reservation_path(reservation) %></td>
	<!-- % if reservation.user == current_user % -->
        <% if true %>
        <td><%= link_to 'Release', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	  <% else %>
	<td></td>
	<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path %>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @reservation.user.email %>
</p>

<p>
  <strong>Asset:</strong>
  <%= @reservation.asset.name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @reservation.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @reservation.end_time %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @reservation.notes %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>