config/routes.rb
Rails.application.routes.draw do
  resources :assets
  resources :reservations
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'reservations#index'
end

app/models/asset.rb
require "rest-client"

class Asset
  include ActiveModel::Model
  #< ApplicationRecord

  #has_many :reservations, dependent: :destroy

  attr_accessor :id,:name,:label,:description,:ip_address

  @@assets=nil

  def initialize(attributes={})
    super
  end

  def self.order(by)
    if @@assets.nil?
      @@assets = self.all
    end
    @@assets
  end

  def self.all
    assets = []
    num = 1
    response = RestClient.get self.uri, :accept=>:json
    json = JSON.parse(response)
    json.each do |s|

      hh = Hash.new
      hh['id'] = s['name']
      hh['name'] = s["name"]
      hh['label'] = "Server-%d" % num
      hh['description'] = "Big Server"
      hh['ip_address'] = "0.0.0.0"

      asset = Asset.new(hh)
      assets << asset
      num += 1
    end
    assets
  end

  def self.find(id)
    #
    asset = nil
    assets = self.all
    assets.each do |aa|
      if aa.id == id
        asset = aa
      end
    end
    asset
  end

  def persisted?
    if id.nil?
      false
    else
      true
    end
  end

  def self.uri
    'http://raj-tmp.ddns.me/api/servers'
  end
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  before_action :set_asset, only: [:show, :edit, :update, :destroy]

  # GET /assets
  # GET /assets.json
  def index
    @assets = Asset.all
  end

  # GET /assets/1
  # GET /assets/1.json
  def show
  end

  # GET /assets/new
  def new
    @asset = Asset.new
  end

  # GET /assets/1/edit
  def edit
  end

  # POST /assets
  # POST /assets.json
  def create
    @asset = Asset.new(asset_params)

    respond_to do |format|
      if @asset.save
        format.html { redirect_to @asset, notice: 'Asset was successfully created.' }
        format.json { render :show, status: :created, location: @asset }
      else
        format.html { render :new }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assets/1
  # PATCH/PUT /assets/1.json
  def update
    respond_to do |format|
      if @asset.update(asset_params)
        format.html { redirect_to @asset, notice: 'Asset was successfully updated.' }
        format.json { render :show, status: :ok, location: @asset }
      else
        format.html { render :edit }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assets/1
  # DELETE /assets/1.json
  def destroy
    @asset.destroy
    respond_to do |format|
      format.html { redirect_to assets_url, notice: 'Asset was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asset
      @asset = Asset.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def asset_params
      params.require(:asset).permit(:ip_address, :label, :description)
    end
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/views/assets/_form.html.erb
<%= form_for(asset) do |f| %>
  <% if asset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(asset.errors.count, "error") %> prohibited this asset from being saved:</h2>

      <ul>
      <% asset.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ip_address %>
    <%= f.text_field :ip_address %>
  </div>

  <div class="field">
    <%= f.label :label %>
    <%= f.text_field :label %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/assets/edit.html.erb
<h1>Editing Asset</h1>

<%= render 'form', asset: @asset %>

<%= link_to 'Show', @asset %> |
<%= link_to 'Back', assets_path %>

app/views/assets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Assets</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Ip address</th>
      <th>Label</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assets.each do |asset| %>
      <tr>
        <td><%= asset.ip_address %></td>
        <td><%= asset.label %></td>
        <td><%= asset.description %></td>
        <td><%= link_to 'Show', asset %></td>
        <td><%= link_to 'Edit', edit_asset_path(asset) %></td>
	<% if current_user.admin? %>
        <td><%= link_to 'Destroy', asset, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<% else %>

	<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Asset', new_asset_path %>

app/views/assets/new.html.erb
<h1>New Asset</h1>

<%= render 'form', asset: @asset %>

<%= link_to 'Back', assets_path %>

app/views/assets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ip address:</strong>
  <%= @asset.ip_address %>
</p>

<p>
  <strong>Label:</strong>
  <%= @asset.label %>
</p>

<p>
  <strong>Description:</strong>
  <%= @asset.description %>
</p>

<%= link_to 'Edit', edit_asset_path(@asset) %> |
<%= link_to 'Back', assets_path %>